language: python
python:
  - 3.3
  - 3.4
  - 3.5
before_install:
  - sudo apt-get install pandoc
install:
  - pip install tox-travis
script:
  - tox
after_success:
  - pytest --cov=doksit
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
